language: node_js
dist: xenial

node_js:
  - "10"

cache:
  directories:
    - node_modules

git:
  depth: 10

jobs:
  include:
    - stage: Static Test
      env:
        - test: Editor Config check
      install:
      - npm ci
      script:
      - npm test
